In [1]:
# manual normalisation

def norm_manual(data):
    n_max = max(data)
    n_min = min(data)
    l_data = len(data)
    
    for i in range(0, l_data):
        data[i] = (data[i] - n_min) / (n_max - n_min)
    
    return data

In [2]:
nilai = [10, 13, 14, 12]
nilai_norm = norm_manual(nilai)
nilai_norm

[0.0, 0.75, 1.0, 0.5]

In [24]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler


In [23]:
data = [
    [100, 0.001],
    [8, 0.005],
    [50, 0.005],
    [88, 0.07],
    [4, 0.1]
]
    
data = np.asarray(data)

scaler = MinMaxScaler()

scaled = scaler.fit_transform(data)
scaled

array([[1.        , 0.        ],
       [0.04166667, 0.04040404],
       [0.47916667, 0.04040404],
       [0.875     , 0.6969697 ],
       [0.        , 1.        ]])

In [21]:
def stand_manual(data):
    n_mean = np.mean(data)
    n_std = np.std(data)
    l_data = len(data)
    
    for i in range(0, l_data):
        data[i] = (data[i] - n_mean) / n_std 
        
    return data

In [22]:
nilai = [10, 13, 14, 12, 19, 20]
nilai_std = stand_manual(nilai)
nilai_std

[-1.2833778958394957,
 -0.45834924851410547,
 -0.1833396994056421,
 -0.7333587976225688,
 1.191708046136675,
 1.4667175952451383]

In [25]:
data = [
    [100, 0.001],
    [8, 0.005],
    [50, 0.005],
    [88, 0.07],
    [4, 0.1]
]

data = np.asarray(data)

scaler = StandardScaler()

scaled = scaler.fit_transform(data)
print(scaled)


[[ 1.26398112 -0.85885341]
 [-1.06174414 -0.76125643]
 [ 0.         -0.76125643]
 [ 0.96062565  0.82469447]
 [-1.16286263  1.55667181]]


In [28]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()

oe = [
    ['State Polytechnics of Malang'],
    ['Electronics State Polytechnics of Surabaya'],
    ['State Polytechnics of Jakarta'],
    ['State Polytechnics of Padang'],
    ['State Polytechnics of Bandung']
]

print(ordinal_encoder.fit_transform(oe))

[[3.]
 [0.]
 [2.]
 [4.]
 [1.]]


In [29]:
from sklearn.feature_extraction import DictVectorizer
onehot_encoder = DictVectorizer()

oe = [
    {'name' : 'State Polytechnics of Malang'},
    {'name' : 'Electronics State Polytechnics of Surabaya'},
    {'name' : 'State Polytechnics of Jakarta'},
    {'name' : 'State Polytechnics of Padang'},
    {'name' : 'State Polytechnics of Bandung'}
]

print(onehot_encoder.fit_transform(oe).toarray())


[[0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]


In [30]:
#ONE HOT ENCODER
from sklearn.preprocessing import OneHotEncoder

oh = OneHotEncoder()

poly = [ 
    ['POLINEMA'],
    ['PENS'],
    ['PNJ'],
    ['POLBAN'],
    ['POLIJE']
]

poly_enc = oh.fit_transform(poly)
poly_enc.toarray()

array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [31]:
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

In [32]:
from posixpath import split


text = 'the house had a tiny little mouse. the cat saw the mouse. the mouse ran away from the house'

split_text = text.split('.')
split_text

['the house had a tiny little mouse',
 ' the cat saw the mouse',
 ' the mouse ran away from the house']

In [33]:
corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')
response = vectorizer.fit_transform(corpus)
print(response)

  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811


In [41]:
print(vectorizer.get_feature_names())

['ate', 'away', 'cat', 'end', 'finally', 'house', 'little', 'mouse', 'ran', 'saw', 'story', 'tiny']
